#!/bin/bash
nvidia-docker run --rm \
-e DISPLAY=$DISPLAY  \
-e QT_X11_NO_MITSHM=1 \
-v /home/$USER:/home/autoware \
-v /tmp/.X11-unix/:/tmp/.X11-unix \
--workdir=/home/autoware \
-i -t \
tieriv/autoware:indigo \
/bin/bash
